name: js-cli-templates-rif
files:
  - 'bin/*.*'
  - '*'
  - '.*'
  - '!rif.config.yaml'
replacements:
  - from: /js-cli-description/g
    to: Git commit message analyse.
  - from: /js-cli/g
    to: '${PROJECT_NAME}'
  - from: /jsc/g
    to: '${PROJECT_NAME}'
